### ISSUE TITLE
loaders

### ISSUE THREAD

**Issue by ankusha-kumar** [Cupcake-Design-System/Cupcake#23]
## Issue Type
Cupcake update

## Description
As a developer, I would like the **loaders** for Cupcake 2.0 to have acceptable API-correct code, written tests, API consistency with 1.0, and match the 2.0 Sketch file design.

## URLs and/or external references
 
URLs: Sketch file

## Classes 

- [ ] .c-skeleton-bar
- [ ] .c-skeleton-loading
- [ ] .c-btn-group-in-progress
- [ ] .c-btn-in-progress
- [ ] .c-overlay-loader
- [ ] .c-full-page-loader

## Acceptance Criteria:

- [ ] Code acceptance: API correct
- [ ] Tests written
- [ ] API consistent with Cupcake 1.x
- [ ] Design match to sketch file

**Comment by ajarvis** [comment]
`.c-full-page-loader` currently inserts a background color behind the loading indicator.  We need an option to use this style loader without the background color as it is often placed on top of various background colors (white, shades of gray, etc).
