### ISSUE TITLE
avatars

### ISSUE THREAD

**Issue by ankusha-kumar** [Cupcake-Design-System/Cupcake#6]
## Issue Type
Cupcake update

## Description
As a developer, I would like the **Avatar** for Cupcake 2.0 to have acceptable API-correct code, written tests, API consistency with 1.0, and match the 2.0 Sketch file design.

## URLs and/or external references
 
URLs: https://ipreo.invisionapp.com/share/P5NNPMKHTR6#/319238398_Avatars

## Classes 

- [x] .c-avatar
- [x]         .c-avatar-danger
- [x]         .c-avatar-lg
- [x]         .c-avatar-primary
- [x]         .c-avatar-secondary
- [x]         .c-avatar-sm
- [x]         .c-avatar-success
- [x]         .c-avatar-warning
- [x]         .c-avatar-xl

## Acceptance Criteria:

- [x] Code acceptance: API correct
- [x] Tests written
- [x] API consistent with Cupcake 1.x
- [x] Design match to sketch file

**Comment by jeaster12** [comment]
closed with #47
